// seedCategories.js
const mongoose = require("mongoose");
const Category = require("./models/categoryModel");

// Kết nối DB
mongoose.connect("mongodb+srv://phanTuoi:phantuoi247@phantuoi.61ma2.mongodb.net/food_app?retryWrites=true&w=majority&appName=phanTuoi", {

});

const categories = [
    { icon: "assets/icons_basic/category/fruit.png", label: "Trái cây" },
    { icon: "assets/icons_basic/category/vegetable.png", label: "Rau củ" },
    { icon: "assets/icons_basic/category/meat.png", label: "Thịt" },
    { icon: "assets/icons_basic/category/seafood.png", label: "Hải sản" },
    { icon: "assets/icons_basic/category/dairy.png", label: "Chế phẩm từ sữa" },
    { icon: "assets/icons_basic/category/dinner.png", label: "Món ăn" },
    { icon: "assets/icons_basic/category/soft-drink.png", label: "Đồ uống" },
    { icon: "assets/icons_basic/category/drink.png", label: "Đồ uống có cồn" },
    { icon: "assets/icons_basic/category/ketchup.png", label: "Nước sốt" },
    { icon: "assets/icons_basic/category/spice.png", label: "Gia vị" },
    { icon: "assets/icons_basic/category/bakery.png", label: "Bánh mì" },
    { icon: "assets/icons_basic/category/ice-cream.png", label: "Tráng miệng" },
    { icon: "assets/icons_basic/category/dried-fruits.png", label: "Quả hạch" },
    { icon: "assets/icons_basic/category/rice.png", label: "Ngũ cốc" },
    { icon: "assets/icons_basic/category/food.png", label: "Vân vân" },
];

const subCategories = {
    "Trái cây": [
        { icon: "assets/icons_basic/fruit/apple.png", label: "Táo" },
        { icon: "assets/icons_basic/fruit/apricot.png", label: "Đào" },
        { icon: "assets/icons_basic/fruit/avocado.png", label: "Bơ" },
        { icon: "assets/icons_basic/fruit/banana.png", label: "Chuối" },
        { icon: "assets/icons_basic/fruit/blueberry.png", label: "Việt quất" },
        { icon: "assets/icons_basic/fruit/berry.png", label: "Cherry" },
        { icon: "assets/icons_basic/fruit/dragon-fruit.png", label: "Thanh long" },
        { icon: "assets/icons_basic/fruit/grapes.png", label: "Nho" },
        { icon: "assets/icons_basic/fruit/grapefruit.png", label: "Bưởi" },
        { icon: "assets/icons_basic/fruit/kiwi.png", label: "Kiwi" },
        { icon: "assets/icons_basic/fruit/lemon.png", label: "Chanh vàng" },
        { icon: "assets/icons_basic/fruit/lime.png", label: "Chanh" },
        { icon: "assets/icons_basic/fruit/durian.png", label: "Sầu riêng" },
        { icon: "assets/icons_basic/fruit/mango.png", label: "Xoài" },
        { icon: "assets/icons_basic/fruit/pear.png", label: "Lê" },
        { icon: "assets/icons_basic/fruit/pineapple.png", label: "Dứa gai" },
        { icon: "assets/icons_basic/fruit/pomegranate.png", label: "Lựu" },
        { icon: "assets/icons_basic/fruit/rambutan.png", label: "Chôm chôm" },
        { icon: "assets/icons_basic/fruit/watermelon.png", label: "Dưa hấu" },
        { icon: "assets/icons_basic/fruit/tomato.png", label: "Cà chua" },
        { icon: "assets/icons_basic/fruit/strawberrry.png", label: "Dâu tây" },
        { icon: "assets/icons_basic/fruit/melon.png", label: "Dưa gang" },
        { icon: "assets/icons_basic/fruit/melon (1).png", label: "Dưa lưới" },
        { icon: "assets/icons_basic/fruit/lychee.png", label: "Vải thiều" },
        { icon: "assets/icons_basic/fruit/persimmon.png", label: "Hồng" },
        { icon: "assets/icons_basic/fruit/papaya.png", label: "Đu đủ" },
        { icon: "assets/icons_basic/fruit/plum.png", label: "Mận" },
        { icon: "assets/icons_basic/fruit/longan.png", label: "Nhãn" },
        { icon: "assets/icons_basic/fruit/coconut.png", label: "Dừa" },
        { icon: "assets/icons_basic/fruit/guava.png", label: "Ổi" },
    ],
    "Rau củ": [
        { icon: "assets/icons_basic/vegetables/chinese-cabbage.png", label: "Cải thảo" },
        { icon: "assets/icons_basic/vegetables/cabbage.png", label: "Bắp cải" },
        { icon: "assets/icons_basic/vegetables/carrots.png", label: "Cà rốt" },
        { icon: "assets/icons_basic/vegetables/onion.png", label: "Hành" },
        { icon: "assets/icons_basic/vegetables/eggplant.png", label: "Cà tím" },
        { icon: "assets/icons_basic/vegetables/pumpkin.png", label: "Bí đỏ" },
        { icon: "assets/icons_basic/vegetables/green-onion.png", label: "Hành lá" },
        { icon: "assets/icons_basic/vegetables/chives.png", label: "Hẹ" },
        { icon: "assets/icons_basic/vegetables/lotus-root.png", label: "Củ sen" },
        { icon: "assets/icons_basic/vegetables/potato.png", label: "Khoai tây" },
        { icon: "assets/icons_basic/vegetables/mushroom.png", label: "Nấm" },
        { icon: "assets/icons_basic/vegetables/oniontay.png", label: "Hành tây" },
        { icon: "assets/icons_basic/vegetables/bok-choy.png", label: "Cải thìa" },
        { icon: "assets/icons_basic/vegetables/sprouts.png", label: "Giá đỗ" },
        { icon: "assets/icons_basic/vegetables/sweet-potato.png", label: "Khoai lang" },
        { icon: "assets/icons_basic/vegetables/cucumber.png", label: "Dưa chuột" },
        { icon: "assets/icons_basic/vegetables/taro.png", label: "Khoai môn" },
        { icon: "assets/icons_basic/vegetables/perilla.png", label: "Tía tô" },
        { icon: "assets/icons_basic/vegetables/corn.png", label: "Ngô" },
        { icon: "assets/icons_basic/vegetables/kohlrabi.png", label: "Su hào" },
        { icon: "assets/icons_basic/vegetables/bingo.png", label: "Bí ngô" },
        { icon: "assets/icons_basic/vegetables/chili.png", label: "Ớt" },
        { icon: "assets/icons_basic/vegetables/bell-pepper.png", label: "Ớt chuông" },
        { icon: "assets/icons_basic/vegetables/cauliflower.png", label: "Súp lơ trắng" },
        { icon: "assets/icons_basic/vegetables/healthy.png", label: "Súp lơ xanh" },
        { icon: "assets/icons_basic/vegetables/green-beans.png", label: "Đậu Cuve" },
        { icon: "assets/icons_basic/vegetables/food.png", label: "Mướp" },
        { icon: "assets/icons_basic/vegetables/zucchini.png", label: "Quả bí" },
        { icon: "assets/icons_basic/vegetables/coriander.png", label: "Rau mùi" },
        { icon: "assets/icons_basic/vegetables/garlic.png", label: "Tỏi" },
        { icon: "assets/icons_basic/vegetables/bitter-gourd.png", label: "Mướp đắng" },
        { icon: "assets/icons_basic/vegetables/basil.png", label: "Húng quế" },
        { icon: "assets/icons_basic/vegetables/spinach.png", label: "Rau muống" },
        { icon: "assets/icons_basic/vegetables/spinach1.png", label: "Rau mồng tơi" },
        { icon: "assets/icons_basic/vegetables/2.png", label: "Rau ngót" },
        { icon: "assets/icons_basic/vegetables/bamboo.png", label: "Măng" },
    ],
    "Thịt": [
        { icon: "assets/icons_basic/meats/pork.png", label: "Ba chỉ heo" },
        { icon: "assets/icons_basic/meats/peking-duck.png", label: "Thịt vịt" },
        { icon: "assets/icons_basic/meats/roast-chicken.png", label: "Thịt gà" },
        { icon: "assets/icons_basic/meats/chicken-wings.png", label: "Cánh gà" },
        { icon: "assets/icons_basic/meats/drumstick.png", label: "Đùi gà" },
        { icon: "assets/icons_basic/meats/ham.png", label: "Giăm bông" },
        { icon: "assets/icons_basic/meats/ribs.png", label: "Sườn" },
        { icon: "assets/icons_basic/meats/tenderloin.png", label: "Thăn bò" },
        { icon: "assets/icons_basic/meats/pork-leg.png", label: "Chân giò heo" },
        { icon: "assets/icons_basic/meats/beef.png", label: "Thịt bò" },
        { icon: "assets/icons_basic/meats/pig.png", label: "Thịt lợn" },
        { icon: "assets/icons_basic/meats/ham1.png", label: "Chế phẩm từ thịt" },
        { icon: "assets/icons_basic/meats/eggs.png", label: "Trứng" },
        { icon: "assets/icons_basic/meats/eggcut.png", label: "Trứng cút" },
        { icon: "assets/icons_basic/meats/tomahawk.png", label: "Bít tết" },
    ],
    "Hải sản": [
        { icon: "assets/icons_basic/seafood/shrimp.png", label: "Tôm" },
        { icon: "assets/icons_basic/seafood/fish.png", label: "Cá" },
        { icon: "assets/icons_basic/seafood/angler.png", label: "Lươn" },
        { icon: "assets/icons_basic/seafood/crab.png", label: "Cua" },
        { icon: "assets/icons_basic/seafood/shell.png", label: "Ốc" },
        { icon: "assets/icons_basic/seafood/clam.png", label: "Ngao" },
        { icon: "assets/icons_basic/seafood/she.png", label: "Hến" },
        { icon: "assets/icons_basic/seafood/mussel.png", label: "Trai" },
        { icon: "assets/icons_basic/seafood/so.png", label: "Sò" },
        { icon: "assets/icons_basic/seafood/squid.png", label: "Mực" },
        { icon: "assets/icons_basic/seafood/salmon.png", label: "Cá hồi" },
        { icon: "assets/icons_basic/seafood/octopus.png", label: "Bạch tuộc" },
        { icon: "assets/icons_basic/seafood/sushi.png", label: "Trứng cá" },
        { icon: "assets/icons_basic/seafood/lobster.png", label: "Tôm hùm" },
        { icon: "assets/icons_basic/seafood/jellyfish.png", label: "Sứa" },
        { icon: "assets/icons_basic/seafood/snow-crab.png", label: "Cua hoàng đế" },
        { icon: "assets/icons_basic/seafood/seaweed.png", label: "Dong biển" },
        { icon: "assets/icons_basic/seafood/clam.png", label: "Ngao" },
    ],
    "Chế phẩm từ sữa": [
        { icon: "assets/icons_basic/dairyMilk/almond-milk.png", label: "Sữa hạnh nhân" },
        { icon: "assets/icons_basic/dairyMilk/cheese.png", label: "Phô mai" },
        { icon: "assets/icons_basic/dairyMilk/bubble-tea.png", label: "Trà sữa" },
        { icon: "assets/icons_basic/dairyMilk/burrata.png", label: "Burrata" },
        { icon: "assets/icons_basic/dairyMilk/butter.png", label: "Bơ sữa" },
        { icon: "assets/icons_basic/dairyMilk/milk.png", label: "Sữa" },
        { icon: "assets/icons_basic/dairyMilk/mozzarella.png", label: "Phô mai Mozzarella" },
        { icon: "assets/icons_basic/dairyMilk/probiotic.png", label: "Probi" },
        { icon: "assets/icons_basic/dairyMilk/yogurt.png", label: "Sữa chua" },
        { icon: "assets/icons_basic/dairyMilk/whipped-cream.png", label: "Kem tươi" },
        { icon: "assets/icons_basic/dairyMilk/corn.png", label: "Sữa ngô" },
        { icon: "assets/icons_basic/dairyMilk/lassi.png", label: "Lassi" },
    ],
    "Đồ uống": [
        { icon: "assets/icons_basic/drink/coke.png", label: "Coca" },
        { icon: "assets/icons_basic/drink/coffee-cup.png", label: "Cà phê" },
        { icon: "assets/icons_basic/drink/orange-juice.png", label: "Nước cam" },
        { icon: "assets/icons_basic/drink/lemonade.png", label: "Nước chanh" },
        { icon: "assets/icons_basic/drink/coconut-drink.png", label: "Nước dừa" },
        { icon: "assets/icons_basic/drink/soft-drink.png", label: "Nước ngọt có ga" },
        { icon: "assets/icons_basic/drink/water-bottle.png", label: "Nước suối" },
        { icon: "assets/icons_basic/drink/energy-drink.png", label: "Nước tăng lực" },
        { icon: "assets/icons_basic/drink/juice.png", label: "Nước ép" },
        { icon: "assets/icons_basic/drink/sport.png", label: "Nước điện giải" },
        { icon: "assets/icons_basic/drink/herbal-tea.png", label: "Trà" },
        { icon: "assets/icons_basic/drink/bubble-tea.png", label: "Trà sữa" },
        { icon: "assets/icons_basic/drink/tea-bag.png", label: "Trà túi lọc" },
        { icon: "assets/icons_basic/drink/ginger-tea.png", label: "Trà gừng" },
        { icon: "assets/icons_basic/drink/hot-chocolate.png", label: "Sôcola nóng" },
        { icon: "assets/icons_basic/drink/lemon-tea.png", label: "Trà chanh" },
    ],
    "Đồ uống có cồn": [
        { icon: "assets/icons_basic/alcohol/beer.png", label: "Bia" },
        { icon: "assets/icons_basic/alcohol/brandy.png", label: "Rượu mạnh" },
        { icon: "assets/icons_basic/alcohol/champagne.png", label: "Sâm panh" },
        { icon: "assets/icons_basic/alcohol/coktail.png", label: "Cocktail" },
        { icon: "assets/icons_basic/alcohol/liqueur-coffee.png", label: "Rượu thảo mộc" },
        { icon: "assets/icons_basic/alcohol/rum.png", label: "Rượu rum" },
        { icon: "assets/icons_basic/alcohol/sangria.png", label: "Rượu hoa quả" },
        { icon: "assets/icons_basic/alcohol/sake.png", label: "Sake" },
        { icon: "assets/icons_basic/alcohol/vodka.png", label: "Vodka" },
        { icon: "assets/icons_basic/alcohol/whiskey.png", label: "Whiskey" },
        { icon: "assets/icons_basic/alcohol/wine-bottle.png", label: "Rượu vang" },
        { icon: "assets/icons_basic/alcohol/soju.png", label: "Soju" },
        { icon: "assets/icons_basic/alcohol/drinks.png", label: "Strongbow" },
    ],
    "Nước sốt": [
        { icon: "assets/icons_basic/sauce/hot-sauce.png", label: "Tương ớt" },
        { icon: "assets/icons_basic/sauce/ketchup.png", label: "Tương cà" },
        { icon: "assets/icons_basic/sauce/sauce12.png", label: "Nước mắm" },
        { icon: "assets/icons_basic/sauce/mayonnaise.png", label: "Mayonnaise" },
        { icon: "assets/icons_basic/sauce/mustard.png", label: "Mù tạt" },
        { icon: "assets/icons_basic/sauce/wasabi.png", label: "Wasabi" },
        { icon: "assets/icons_basic/sauce/soy-sauce.png", label: "Xì dầu" },
        { icon: "assets/icons_basic/sauce/soy-sauce1.png", label: "Tương bần" },
        { icon: "assets/icons_basic/sauce/honey.png", label: "Mật ong" },
        { icon: "assets/icons_basic/sauce/sauce.png", label: "Sốt BBQ" },
        { icon: "assets/icons_basic/sauce/rice-wine.png", label: "Giấm gạo" },
        { icon: "assets/icons_basic/sauce/apple-cider-vinegar.png", label: "Giấm táo" },
        { icon: "assets/icons_basic/sauce/jam.png", label: "Mứt dâu" },
    ],
    "Gia vị": [
        { icon: "assets/icons_basic/spices/salt.png", label: "Muối" },
        { icon: "assets/icons_basic/spices/chilli-pepper.png", label: "Bột ớt" },
        { icon: "assets/icons_basic/spices/sugar.png", label: "Đường" },
        { icon: "assets/icons_basic/spices/cinnamon.png", label: "Quế" },
        { icon: "assets/icons_basic/spices/food.png", label: "Bột nghệ" },
        { icon: "assets/icons_basic/spices/ginger.png", label: "Gừng" },
        { icon: "assets/icons_basic/spices/lemongrass.png", label: "Sả" },
        { icon: "assets/icons_basic/spices/pepper.png", label: "Tiêu" },
        { icon: "assets/icons_basic/spices/chili-sauce.png", label: "Sa tế" },
        { icon: "assets/icons_basic/spices/salt-and-pepper.png", label: "Hạt nêm" },
        { icon: "assets/icons_basic/spices/monosodium-glutamate.png", label: "Bột ngọt" },
    ],
    "Bánh mì": [
        { icon: "assets/icons_basic/bread/bagel.png", label: "Bánh mì vòng" },
        { icon: "assets/icons_basic/bread/bread.png", label: "Bánh mì" },
        { icon: "assets/icons_basic/bread/bread_circle.png", label: "Bánh mì tròn" },
        { icon: "assets/icons_basic/bread/brioche.png", label: "Bánh mì Brioche" },
        { icon: "assets/icons_basic/bread/donut.png", label: "Donut" },
        { icon: "assets/icons_basic/bread/sandwich.png", label: "Sandwich" },
        { icon: "assets/icons_basic/bread/sandwich_1.png", label: "Bánh mì pate" },
        { icon: "assets/icons_basic/bread/pizza.png", label: "Pizza" },
        { icon: "assets/icons_basic/bread/bread-loaf.png", label: "Bánh mì sandwich" },
        { icon: "assets/icons_basic/bread/pancakes.png", label: "Pancake" },
    ],
    "Tráng miệng": [
        { icon: "assets/icons_basic/desserts/tong-sui.png", label: "Chè" },
        { icon: "assets/icons_basic/desserts/ice-cream.png", label: "Kem" },
        { icon: "assets/icons_basic/desserts/strawberry-cake.png", label: "Bánh ngọt" },
        { icon: "assets/icons_basic/desserts/egg-tart.png", label: "Bánh tar trứng" },
        { icon: "assets/icons_basic/desserts/chocolate.png", label: "Sô cô la" },
        { icon: "assets/icons_basic/desserts/candy.png", label: "Kẹo" },
        { icon: "assets/icons_basic/desserts/caramel.png", label: "Caramel" },
        { icon: "assets/icons_basic/desserts/chewing-gum.png", label: "Kẹo cao su" },
        { icon: "assets/icons_basic/desserts/cookie.png", label: "Bánh quy" },
        { icon: "assets/icons_basic/desserts/energy-bar.png", label: "Thanh năng lượng" },
        { icon: "assets/icons_basic/desserts/caramel-pudding.png", label: "Pudding" },
        { icon: "assets/icons_basic/desserts/swiss-roll.png", label: "Bánh cuộn" },
        { icon: "assets/icons_basic/desserts/potato-chips.png", label: "Snack khoai tây" },
        { icon: "assets/icons_basic/desserts/snack.png", label: "Bim bim" },
        { icon: "assets/icons_basic/desserts/moon-cake.png", label: "Bánh trung thu" },
    ],
    "Quả hạch": [
        { icon: "assets/icons_basic/nuts/snack.png", label: "Hạt bí" },
        { icon: "assets/icons_basic/nuts/sunflower-seed.png", label: "Hạt hướng dương" },
        { icon: "assets/icons_basic/nuts/cashew.png", label: "Hạt điều" },
        { icon: "assets/icons_basic/nuts/nut.png", label: "Hạt óc chó" },
        { icon: "assets/icons_basic/nuts/almond.png", label: "Hạnh nhân" },
        { icon: "assets/icons_basic/nuts/chestnut.png", label: "Hạt dẻ" },
        { icon: "assets/icons_basic/nuts/macadamia.png", label: "Mắc ca" },
        { icon: "assets/icons_basic/nuts/peanuts.png", label: "Đậu phộng" },
        { icon: "assets/icons_basic/nuts/healthy.png", label: "Đậu nành" },
        { icon: "assets/icons_basic/nuts/lotus.png", label: "Hạt sen" },
        { icon: "assets/icons_basic/nuts/pistachio.png", label: "Hạt dẻ cười" },
        { icon: "assets/icons_basic/nuts/cacao.png", label: "Cacao" },
    ],
    "Ngũ cốc": [
        { icon: "assets/icons_basic/grains/rice.png", label: "Gạo" },
        { icon: "assets/icons_basic/grains/beans.png", label: "Đậu đen" },
        { icon: "assets/icons_basic/grains/red-beans.png", label: "Đậu đỏ" },
        { icon: "assets/icons_basic/grains/cereal.png", label: "Yến mạch" },
        { icon: "assets/icons_basic/grains/millet.png", label: "Hạt kê" },
        { icon: "assets/icons_basic/grains/bag.png", label: "Lúa mạch" },
        { icon: "assets/icons_basic/grains/brown-rice.png", label: "Gạo lứt" },
        { icon: "assets/icons_basic/grains/cornHat.png", label: "Hạt ngô" },
    ],
};

async function seed() {
    try {
        await Category.deleteMany(); // Xóa dữ liệu cũ cho sạch

        for (const cat of categories) {
            const subs = subCategories[cat.label] || [];
            await Category.create({
                icon: cat.icon,
                label: cat.label,
                subCategories: subs,
            });
        }

        console.log("Seed categories thành công!");
        process.exit();
    } catch (err) {
        console.error("Lỗi seed:", err);
        process.exit(1);
    }
}

seed();
